packages:
  - package: dbt-labs/dbt_utils
    version: 1.4.1
  - git: https://github.com/dbt-labs/dbt-codegen.git
    revision: main
  - package: dbt-labs/audit_helper
    version: 0.14.0
  - package: selectstar/snowflake_spend
    version: 1.4.0